# Generated by Django 5.2.3 on 2025-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("User", "User"), ("Admin", "Admin"), ("Manager", "Manager")],
                default="user",
                max_length=20,
            ),
        ),
    ]
